### ISSUE TITLE
Chart yields invalid telegraf.conf when using nested config

### ISSUE THREAD

**Issue by MarianSaeger** [influxdata/tick-charts#22]
Hi!

I noticed a behaviour of helm which, in context of telegraf tick charts, yields an invalid telegraf.conf.

For example, when adding `cloudwatch` as input, with a metrics filter, like this:

```
    [...]
    cloudwatch:
      region: "us-east-1"
      access_key: "someaccesskey"
      secret_key: "somesecret"
      period: "5m"
      delay: "5m"
      interval: "5m"
      cache_ttl: "10m"
      namespace: "AWS/ELB"
      ratelimit: 10
      metrics:
        names:
        - "Latency"
        - "RequestCount"
        dimensions:
          name: "LoadBalancerName"
          value: "p-example"
    [...]
```
a call to  
`helm install --dry-run --debug telegraf-s/` (untared into local folder)
shows this:
```
  [[inputs.cloudwatch]]
    access_key = "someaccesskey"
    cache_ttl = "10m"
    delay = "5m"
    interval = "5m"
    [[inputs.cloudwatch.metrics]]
      [[inputs.cloudwatch.metrics.dimensions]]
          name = "LoadBalancerName"
          value = "p-example"
      names = [
          "Latency",
          "RequestCount"
      ]
    namespace = "AWS/ELB"
    period = "5m"
    ratelimit = 10
    region = "us-east-1"
    secret_key = "somesecret"
```

According to https://github.com/influxdata/telegraf/blob/master/docs/CONFIGURATION.md#input-config-tags this format is invalid:

"NOTE: Order matters, the `[inputs.cpu.tags]` table must be at the end of the plugin definition."

Apparently, helm reorders the values alphanumerically, which is unfortunate, as the template does not take these hierarchical values into consideration when rendering the template.
